management:
  endpoint:
    health:
      group:
        liveness:
          include: livenessProbe
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
server:
  shutdown:
    grace-period: 30s